# Generated by Django 3.2.19 on 2023-05-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.australiancatering.com.au/themes/frontend/default/images/img-placeholder.png', max_length=500),
        ),
    ]
